FROM python:3.12-slim

ARG SERVICE_DIR

ENV SERVICE_DIR=${SERVICE_DIR} \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /workspace

COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/${SERVICE_DIR}/requirements.txt

WORKDIR /workspace/${SERVICE_DIR}

